version: "3"
services:
  fastpages: &fastpages
    working_dir: /data
    environment:
        - INPUT_BOOL_SAVE_MARKDOWN=false
    build:
      context: ./_action_files
      dockerfile: ./Dockerfile
    image: fastpages-dev
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/data/

  converter:
    <<: *fastpages
    command: /fastpages/action_entrypoint.sh

  # 2020-05-22 <mhucka@caltech.edu> Don't need until I have notebook pages.
  # watcher:
  #   <<: *fastpages
  #   command: watchmedo shell-command --command /fastpages/action_entrypoint.sh --pattern *.ipynb --recursive --drop

  jekyll:
    working_dir: /data
    image: hamelsmu/fastpages-jekyll
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/data/
      # 2020-05-22 <mhucka@caltech.edu> I tried adding --livereload to jekyll
      # but, even though pages were regenerated automatically, my browser did
      # not refresh changed pages automatically.
    command: >
     bash -c "gem install bundler
     && jekyll serve --incremental --verbose --trace --strict_front_matter"
